name: enigma2-plugins build

on:
  push:
    branches: [ master, python3 ]
  pull_request:
    branches: [ master, python3 ]

jobs:
  build:
    name: Build enigma2-plugins
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: [8, 9, 10]
    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get install automake
          sudo apt-get install build-essential
          sudo apt-get install gettext
          sudo apt-get install g++-${{ matrix.gcc }}

      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build plugins, gcc-${{ matrix.gcc }}, python 2.7
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          sed -i '/PKG_CHECK_MODULES(ENIGMA2, enigma2)/d' ./configure.ac
          sed -i '/PKG_CHECK_MODULES(GSTREAMER, gstreamer-$GST_MAJORMINOR gstreamer-pbutils-$GST_MAJORMINOR)/d' ./configure.ac
          sed -i '/PKG_CHECK_MODULES(LIBCRYPTO, libcrypto)/d' ./configure.ac
          autoreconf -i
          ./configure --without-debug --with-po
          make
          python -m compileall .

      - uses: actions/checkout@v2
        with:
          ref: 'python3'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build plugins, gcc-${{ matrix.gcc }}, python 3.8
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          pip3 install six
          sed -i '/PKG_CHECK_MODULES(ENIGMA2, enigma2)/d' ./configure.ac
          sed -i '/PKG_CHECK_MODULES(GSTREAMER, gstreamer-$GST_MAJORMINOR gstreamer-pbutils-$GST_MAJORMINOR)/d' ./configure.ac
          sed -i '/PKG_CHECK_MODULES(LIBCRYPTO, libcrypto)/d' ./configure.ac
          autoreconf -i
          ./configure --without-debug --with-po
          make
          python -m compileall .
